### PR TITLE
Fixes for new CI

### PR DESCRIPTION
**Pull request by tnozicka**
CI is gonna move from TravisCI to OpenShift CI giving us huge improvements. Need to transition few things first.

### CODE REVIEW

**Comment by LorbusChris** [comment]
Thanks for working on this, @tnozicka, persevere! Are you by any chance in Brno this week? Would love to have a chat!

**Comment by disappear89** [comment]
> @LorbusChris I am giving a talk at DevConf.cz about openshift-acme on Friday, feel free to find me there.
> 
> just for an update: I am trying to debug the openshift clusters spinning from e2e but something in GCP is still killing the connection when reaching back from the cluster to the LB before router

Hey, had also strange disconnect issues, maybe this two hints can help you:
1. Make sure that your instances got low mtu setting cause GCP needs some space for its own SDN, i think default MTU is 1.460 see: https://cloud.google.com/vpn/docs/concepts/mtu-considerations
2. If you use GCP load balancers us high timeout settings example:
image

**Pull request merged**
