### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by tnozicka**
Switch controller to all the fancy stuff like shared informers and work queue, move to glide, use global ACME account.

Fixes: https://github.com/tnozicka/openshift-acme/issues/47 https://github.com/tnozicka/openshift-acme/issues/42 https://github.com/tnozicka/openshift-acme/issues/38 https://github.com/tnozicka/openshift-acme/issues/29 https://github.com/tnozicka/openshift-acme/issues/28 https://github.com/tnozicka/openshift-acme/issues/27 https://github.com/tnozicka/openshift-acme/issues/17 https://github.com/tnozicka/openshift-acme/issues/16 https://github.com/tnozicka/openshift-acme/issues/12 https://github.com/tnozicka/openshift-acme/issues/7 https://github.com/tnozicka/openshift-acme/issues/5

Not yet ready for code review as I need to clean up the code; although the high level logic should stay.

For those wanting to try it out the HEAD of this branch is continuously pushed to `docker.io/tnozicka/openshift-acme:v0.8.0-pre-alpha`.

If you want to deploy it directly from GitHub use:

```bash
oc create -fhttps://raw.githubusercontent.com/tnozicka/openshift-acme/rewrite/deploy/letsencrypt-staging/cluster-wide/{clusterrole,serviceaccount,imagestream,deployment}.yaml
oc adm policy add-cluster-role-to-user openshift-acme -z openshift-acme
oc patch is openshift-acme -p '{"spec":{"tags":[{"name":"latest","from":{"name":"docker.io/tnozicka/openshift-acme:v0.8.0-pre-alpha"}}]}}'
```

or modify one of the deploy ways in https://github.com/tnozicka/openshift-acme/tree/rewrite/deploy similarly

TODO:
- [x] Drop the "DROP: ..." commit(s)
- [x] Sync the certificate also to a Secret + test
- [x] Cleanup the code
- [x] Extended test for certificate renewal

### CODE REVIEW

**Comment by twhiston** [comment]
for my own interest: is there a reason you switched to glide for this, considering that on the glide page they tell you to use dep if possible? Would be interested to know what motivated the decision.

**Comment by tnozicka** [comment]
> for my own interest: is there a reason you switched to glide for this, considering that on the glide page they tell you to use dep if possible? Would be interested to know what motivated the decision.

@twhiston I liked `dep` before I found out that it doesn't support transitive dependencies which makes it unusable for bigger projects, especially when you need to vendor e.g. kubernetes. We had the same discussion in OpenShift few weeks back and we switched to glide as well for the same reasons. `dep` is just not ready yet :/

**Comment by twhiston** [comment]
That is really a interesting discussion (and threw me down a rabbit hole of github issues ;) ) thanks for enlightening me!

**Comment by tnozicka** [comment]
Issues should be sorted out. Tests are green. Whoever feels like it PTAL. 

Given the fact that this pull is add 2.1+ million of lines and removing about 0.5 million I guess running it and reporting back is the most realistic approach here. (I don't really expect someone to go through the pain of reviewing this.)

I'd like to merge this soon and build on top of it. (This giant PR is just scary.) Can't say this is without potential bugs but I am of the opinion that this is miles before what we have in master.

**Comment by tnozicka** [comment]
So not to discourage you completely the important commit with changes is <10k lines changed :)

**Comment by tnozicka** [comment]
With the temporary objects now being deleted on success I think this is ready to go.

**Pull request merged**
