### PR TITLE
implement router sharding support

### LINKED ISSUE #45: Add support for route labels (router sharding)
I'm running two OS3 routers: one "internal", one "public". The public router and routes exposed therein are accessible from the internet, the internal one is for LAN-only.

The public router only exposes routes that are labelled with (`router=public` (ENV `ROUTE_LABELS=router=public`)).

When `openshift-acme` creates the temporary `.well-known` route, it will be created without the `router` label and hence exposed on the local router. LetsEncrypt tries to verify the challenge, but gets a 404 response and fails.

Is there any way to work around this and tell `openshift-acme` the default labels the challenge route should get? Currently, I'm forced to disable `ROUTE_LABELS` and expose all routes to the Interwebs.

### PR DESCRIPTION
**Pull request by tanskann**
Fixes #45 by making it possible to configure labels to challenge URL

### CODE REVIEW

**Comment by tanskann** [comment]
Seems for me that the build is triggered for `go version go1.7.4 linux/amd64` which I guess is unwanted. By fixing the CI it should show green light.

Same thing happening with current open pull requests.

**Comment by aramalipoor** [comment]
Any updates on this?

**Comment by foosinn** [comment]
i would also like to see this merged. is there anything we can help with?

**Comment by tnozicka** [comment]
```
Conflicting files
pkg/cmd/cmd.go
```
this conflict needs to be solved first, or the test keep failing

**Comment by LorbusChris** [comment]
@tanskann would you mind rebasing?
/remove-lifecycle rotten

**Comment by tanskann** [comment]
@LorbusChris I'll try to find some time this week

**Comment by tnozicka** [comment]
v2 rewrite in https://github.com/tnozicka/openshift-acme/pull/92 deep copies the original route so it gets any labels set on the original route - I think that should cover the use case, right?

We also don't get successful CI runs until that's merged as LE disabled staging and now also live v1 registrations.

As I think https://github.com/tnozicka/openshift-acme/pull/92 fixes the issue and also outdated the code modified here, I'll close this PR.

**Pull request closed without merging**
